version: '3'
services:
  hedron-db:  # Updated service name
    image: postgres:latest
    container_name: hedron-db  # Updated container name
    environment:
      POSTGRES_DB: hedron-db  # Updated database name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hedron-back:  # Updated service name
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Path to your Dockerfile (if it's in the same directory)
    container_name: hedron-back  # Updated container name
    ports:
      - "8080:8080"
    depends_on:
      - hedron-db  # Updated service name in dependency
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://hedron-db:5432/hedron-db  # Updated database name
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres-data:
